# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class Coordinates(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, lat=None, lon=None):  # noqa: E501
        """Coordinates - a model defined in OpenAPI

        :param lat: The lat of this Coordinates.  # noqa: E501
        :type lat: float
        :param lon: The lon of this Coordinates.  # noqa: E501
        :type lon: float
        """
        self.openapi_types = {
            'lat': float,
            'lon': float
        }

        self.attribute_map = {
            'lat': 'Lat',
            'lon': 'Lon'
        }

        self._lat = lat
        self._lon = lon

    @classmethod
    def from_dict(cls, dikt) -> 'Coordinates':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Coordinates of this Coordinates.  # noqa: E501
        :rtype: Coordinates
        """
        return util.deserialize_model(dikt, cls)

    @property
    def lat(self):
        """Gets the lat of this Coordinates.


        :return: The lat of this Coordinates.
        :rtype: float
        """
        return self._lat

    @lat.setter
    def lat(self, lat):
        """Sets the lat of this Coordinates.


        :param lat: The lat of this Coordinates.
        :type lat: float
        """
        if lat is None:
            raise ValueError("Invalid value for `lat`, must not be `None`")  # noqa: E501

        self._lat = lat

    @property
    def lon(self):
        """Gets the lon of this Coordinates.


        :return: The lon of this Coordinates.
        :rtype: float
        """
        return self._lon

    @lon.setter
    def lon(self, lon):
        """Sets the lon of this Coordinates.


        :param lon: The lon of this Coordinates.
        :type lon: float
        """
        if lon is None:
            raise ValueError("Invalid value for `lon`, must not be `None`")  # noqa: E501

        self._lon = lon
